---
title: "Data Cleaning"
format: html
---
All data used in this project came from a simulated dataset regarding ACLR recovery. The simulated data was based on patient data compiled by School of Data Science and the Department of Kinesiology at the University of Virginia. To explore our guiding question, we filtered and cleaned the dataset as below:


First, we imported our dependencies and loaded in the original dataset
```{python}
#import dependencies
import pandas as pd
```
```{python}
#load in the data
aclr_orig = pd.read_csv('aclr_data.csv')
```


Second, we dropped all columns that weren't relevant to our guiding question. We included strength measurements as well as demographics that might impact recovery
```{python}
col_list = ['record_id', 'sex_dashboard', 'age', 'age_group', 'tss', 'tss_dashboard', 'ikdc', 'acl_rsi']
lsi_list = [col for col in aclr_orig.columns if 'lsi' in col and '_l' not in col]
final_list = col_list + lsi_list
aclr_used = aclr_orig[final_list]
```


Since the data was longitudinal, we could fill in some missing data using 'record_id', which identified unique patients. Values for sex and age group were filled in this way:
```{python}
aclr = aclr_used.copy()
# Update to use .ffill() and .bfill() directly
aclr['sex_dashboard'] = aclr.groupby('record_id')['sex_dashboard'].transform(lambda x: x.ffill().bfill())
aclr['age_group'] = aclr.groupby('record_id')['age_group'].transform(lambda x: x.ffill().bfill())
```


Age group was converted to a categorical variable
```{python}
aclr['age_group'] = aclr['age_group'].astype('category')
```


Due to the nature of the data, i.e. patients having multiple visits and various strength tests being used in different combinations, we chose not to drop rows with NA values. This gives u the most data possible to work with when drawing conclusions.


```{python}
aclr.to_csv('cleaned_aclr_data.csv', index=False)
```


