# Report {.unnumbered}

## Prepared for {.unnumbered}

This report was made to help doctors, physical therapists, or any clinician who works with ACLR patients during recovery. Our focus was to offer insight into how flexion and extension strength progress over time after surgery.

## Problem Statement

The knee has two primary functions: flexion and extension. Both these strengths can be measured isokinetically or isometrically, and at varying degrees. After injury, and even after surgery, both these strengths have decreased in the affected limb. Rehabilitation aims to get a patient’s knee strengths back to where they were before surgery. To explore the successes and failures of rehab, we asked the following questions:
* Do flexion strength and extension strength progress differently during recovery?
* How might strength tests relate to more holistic measures of recovery, such as ACL-RSI?


## Analysis

 [use storytelling and visuals to show how you are answering the problem]

## Conclusion

 [use storytelling to give your conclusions and/or action items, can include a visual]